### ISSUE TITLE
Is Round Robin Assigner compatible with the new @AuraEnabled security update?

### ISSUE THREAD

**Issue by scaracand** [mshanemc/roundRobinProcessBuilder#19]
Salesforce intends to release a critical update to Apex classes containing an @AuraEnabled method so that an authenticated user can access an @AuraEnabled Apex method only when the user’s profile allows access to the Apex class. In Winter ‘21, Salesforce will automatically activate the critical update for all orgs. This critical update enforces user profile restrictions for Apex classes used by Aura and Lightning web components. Authenticated users will need to have permission in their profiles or permission sets to access an Apex class. Aura or Lightning web components that call @AuraEnabled methods contained in these Apex classes may fail to load or operate correctly.

**Comment by mshanemc** [comment]
There are no AuraEnabled methods in the project.
