### ISSUE TITLE
Not an Issue, just looking for Flow Instructions

### ISSUE THREAD

**Issue by MaxinitoEl** [mshanemc/roundRobinProcessBuilder#31]
Thank you for creating this valuable app. I found Process Builder instructions but nothing for Flow. Do you have Flow instructions for Round Robin Assigner?

Thanks!

**Comment by robertjr23** [comment]
Not sure if you have your answer, but after creating your public group and assigning the respective users, you'll add an element into your flow. Under 'Interaction' select action, filter by type, choose 'Apex Action', and you'll find 'Assign Objects' if you successfully installed the managed package via the AppExchange Market Place. Similar to the Process Builder Instructions, you'll select the group name (not the API name) as well as the record id you plan on updating the ownership on, ex. record.account.id.

**Comment by MaxinitoEl** [comment]
Thank you, Robert!
