### ISSUE TITLE
OwnerID not editable

### ISSUE THREAD

**Issue by leosden40** [mshanemc/roundRobinProcessBuilder#4]
That is the error I get when trying to save a case. I followed the instructions to the T as well. What could be happening?

**Comment by cgh91b30** [comment]
Having same issue.

**Comment by melissa-shook** [comment]
I had the same issue and then I saw the Setup Instruction post  by YINT2018. They clarified step 5. Specify the group name (label, not API name) and the **recordId (the record id field of the records you want to reassign, Opportunity.id,lead.id etc.)**  I had been using the record ID of the Group. When I changed it to a field reference of Contact.ID, it worked.

**Comment by d0rpho** [comment]
> I had the same issue and then I saw the Setup Instruction post by YINT2018. They clarified step 5. Specify the group name (label, not API name) and the **recordId (the record id field of the records you want to reassign, Opportunity.id,lead.id etc.)** I had been using the record ID of the Group. When I changed it to a field reference of Contact.ID, it worked.

I did all the steps and i'm still getting error, could you have any print screen or anything to help.. please :)

**Comment by mshanemc** [comment]
@d0rpho can you screenshot your process builder setup?

**Comment by d0rpho** [comment]
Hi all, i fix it.. Now I have to decide if i keep in assignment rule using two custom fields or builder with this great app lol thank you all for help

**Comment by mshanemc** [comment]
Great!
